### ISSUE TITLE
There are errors in the logs after the version >= 2.2.6

### ISSUE THREAD

**Issue by shgubar** [sunfounder/pironman#16]
Hi

Thank you for fixing bugs and modernizing the code.

I installed the latest version **2.2.6**, but I see the following problem in the logs:
`24/02/27 15:23:37,327 [DEBUG] DigitalOutputDevice is closed or uninitialized`

Here is the full log after launch:
```
-----------------------24/02/27 15:23:37------------------------
pironman version: 2.2.6
username: pi
config_file: /opt/pironman/config.txt

Kernel Version:
Linux RaspSERV 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux

24/02/27 15:23:37,326 [DEBUG] error
24/02/27 15:23:37,327 [DEBUG] DigitalOutputDevice is closed or uninitialized
OS Version:
Description:    Debian GNU/Linux 12 (bookworm)

PCB info:
Revision        : d03115
Model           : Raspberry Pi 4 Model B Rev 1.5

24/02/27 15:23:37,335 [DEBUG] power_key_pin : 16
24/02/27 15:23:37,335 [DEBUG] fan_pin : 6
24/02/27 15:23:37,335 [DEBUG] update_frequency : 0.5
24/02/27 15:23:37,335 [DEBUG] temp_unit : C
24/02/27 15:23:37,335 [DEBUG] fan_temp : 30.0
24/02/27 15:23:37,335 [DEBUG] screen_always_on : False
24/02/27 15:23:37,335 [DEBUG] screen_off_time : 30
24/02/27 15:23:37,336 [DEBUG] rgb_enable : False
24/02/27 15:23:37,336 [DEBUG] rgb_style : breath
24/02/27 15:23:37,336 [DEBUG] rgb_color : 0a1aff
24/02/27 15:23:37,336 [DEBUG] rgb_blink_speed : 50
24/02/27 15:23:37,336 [DEBUG] rgb_pwm_freq : 1000
24/02/27 15:23:37,336 [DEBUG] rgb_pin : 10
>>>
24/02/27 15:23:37,346 [DEBUG] rgb_strip init success
24/02/27 15:23:37,347 [DEBUG] close_rgb in sys.argv
24/02/27 15:23:37,347 [DEBUG] rgb_strip clear
```

When I change the parameters, sometimes the service does not start at all, but in the logs it says:
```
------------------------24/02/27 15:36:52------------------------
pironman version: 2.2.6
username: pi
config_file: /opt/pironman/config.txt

Kernel Version:
Linux RaspSERV 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux

PCB info:
Revision        : d03115
Model           : Raspberry Pi 4 Model B Rev 1.5

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
          ~~~~~~~~~^^^^^^
KeyError: PinInfo(number=31, name='GPIO6', names=frozenset({'BOARD31', '6', 6, 'GPIO6', 'BCM6', 'J8:31', 'WPI22'}), pull='', row=16, col=1, interfaces=frozenset({'', 'spi', 'gpio', 'i2c', 'uart', 'smi', 'dpi'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pironman/main.py", line 69, in <module>
    fan = Fan(fan_pin)
          ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 192, in __init__
    super().__init__(pin, active_high=active_high,
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 74, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/lgpio.py", line 126, in __init__
    lgpio.gpio_claim_input(
  File "/usr/lib/python3/dist-packages/lgpio.py", line 755, in gpio_claim_input
    return _u2i(_lgpio._gpio_claim_input(handle&0xffff, lFlags, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO busy'
```

Currently reverted to version **2.2.4** - works more stable at this moment, although there is a bug with reading CPU usage.
Maybe some more data is needed to determine the problem. Let me know.

**Comment by shgubar** [comment]
Same errors in `2.2.7` and `2.2.8` versions:
```
[DEBUG] error
[DEBUG] DigitalOutputDevice is closed or uninitialized
```
